### ISSUE TITLE
Multiple "spelling" columns

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#588] opened 2016-07-07 03:35 UTC
In creating the csv_sample corpus or the ilg_sample corpus (possibly others?), the corpus loads correctly, but ends up with two spelling columns. The order is spelling / transcription / spelling / frequency. I wonder if this is related to trying to re-arrange the order so that spelling comes first? (But now comes both first and third?) They aren't the same column, though -- if I set the name of the spelling column when creating the corpus to be something other than "Spelling," the first column gets that name and the third one is called "Spelling." Though that also raises another issue…. #589

(Interestingly, I still get two "spelling" columns even with the running text corpus, even though the only tier specified was transcription….)

**Comment by jsmackie** [comment] 2016-07-07 23:46
This was caused by a bug that incorrectly categorized some spelling colums as factory-type instead of spelling-type. This has been fixed now.

**Closed by jsmackie** 2016-07-07 23:46 UTC
Labels: bug
