### ISSUE TITLE
error loading a running text corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#573] opened 2016-07-01 00:37 UTC
Trying to create a running text corpus, where there is just transcribed text:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 79, in run
    corpus = load_discourse_transcription(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_transcription.py", line 216, in load_discourse_transcription
    data = transcription_text_to_data(path, annotation_types, stop_check=stop_check, call_back=call_back)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_transcription.py", line 105, in transcription_text_to_data
    trans = parse_transcription(word, data[n])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/helper.py", line 160, in __getitem__
    return self.data[key]
KeyError: 'transcription'

Here's the text file: 
[running_text_sample_nondelimited_digraphs.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/342618/running_text_sample_nondelimited_digraphs.txt)

**Comment by kchall** [comment] 2016-07-03 20:00
Hmm, I can now load the corpus with no problem, which is good, but there are still two odd things:

1. (Definitely a bug) -- if I try to set the sequence [sh] to be a digraph, PCT fails to do so; it delimits it in the created corpus as [s.h].

2. The inventory that pops up when I load the corpus with ipa2hayes features looks like inventory from the example corpus, and in particular, it includes the segment [ʃ], which does not actually occur in the inventory of this corpus. If I click on this segment in the summary, it doesn't indicate that it has a type or token frequency, but it's odd that it even appears.

**Comment by jsmackie** [comment] 2016-07-04 04:44
I had no problem loading this corpus correctly. When you click the "Running text" tab in the corpus loading window, there's an option underneath that says "text type". Make sure you set that to transcription, because it apparently doesn't matter what you put into the parsing preview window - the text type box takes precedence. If you choose text type Orthography, but then make your stuff Transcription in the parsing preview window, then it will raise an error.

**Comment by kchall** [comment] 2016-07-04 05:32
Hmm, this is odd. I double-checked and made sure to set it to Transcription, and still initially got exactly the same problems (i.e., loading, not recognizing [sh], and erroneously including [ʃ]). I quit PCT, re-synced, and re-started, and this time it worked except for still not recognizing [sh] as a sequence; it counts [s] and [h] separately, despite my very definitely indicating that should be a digraph. I'm attaching screenshots for reference.


[issue_573_screenshots.pdf](https://github.com/PhonologicalCorpusTools/CorpusTools/files/345652/issue_573_screenshots.pdf)

**Comment by jsmackie** [comment] 2016-07-04 18:53
I see that there is a problem with the digraphs, and they aren't being recognised at all, regardless of what kind of corpus you try to import. Didn't this used to work? There's a function called compile_digraphs which is imported but never used, which is odd. I'm looking into this right now.

I don't understand why you'd be getting  [ʃ], however. That's just too weird to explain. I'm glad it disappeared after a restart. 

Having /h/ appear as uncategorized is not a bug (aside from the fact that it should have been in a digraph with /s/). It turns out that /h/ doesn't match any of the preset categories, but those can be changed. How should /h/ be categorized? Glottal fricative?

As an aside, I added a little check to the corpus loading window to see if the running text type (orthography/transcription) matches with the Annotation Types in the parsing preview window. This should prevent any errors caused by mismatches.

**Comment by jsmackie** [comment] 2016-07-04 20:11
The digraph issue is fixed with a recent commit. I'm hoping the [ʃ] problem was a one-off that was fixed with your reset.

**Closed by jsmackie** 2016-07-04 20:11 UTC
Labels: bug, High priority
